name: CI/CD Pipeline

on:
  push:
    branches:
#      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

#    - name: Run tests
#      run: |
#        pip install pytest
#        pytest

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-flask-api .

      ## ToDo
#        1. Publish to container registry
#        2. Run Vulnerability tests
#        3.
    - name: Run Docker container
      run: docker run -d -p 5000:5000 my-flask-api

    - name: Integration tests
      run : |
        # Wait for the container to be up and running
        sleep 10
        # Run integration tests against the running container
        curl --fail http://localhost:5000/ || exit 1

    - name: Stop and remove container
      run: docker rm -f my-flask-api-container